apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBCluster"
metadata:
  name: "some-name"
  finalizers:
    - delete-pxc-pods-in-order
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster-operator:0.3.0-pxc
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
      limits:
        memory: "1G"
        cpu: "1"
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  proxysql:
    enabled: true
    size: 1
    image: percona/percona-xtradb-cluster-operator:0.3.0-proxysql
    resources:
      requests:
        memory: 0.1G
        cpu: 100m
      limits:
        memory: 1G
        cpu: 700m
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
  pmm:
    enabled: false
    image: perconalab/pmm-client:1.17.1
    serverHost: monitoring-service
    serverUser: pmm
  backup:
    image: percona/percona-xtradb-cluster-operator:0.3.0-backup
    storages:
      aws-s3:
        type: s3
        s3:
          region: us-east-1
          bucket: operator-testing
          credentialsSecret: aws-s3-secret
      pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
              resources:
                requests:
                  storage: 1Gi
