apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  generation: 1
  name: no-proxysql-pxc
  ownerReferences:
  - apiVersion: apps/v1
    controller: true
    kind: StatefulSet
    name: no-proxysql-pxc
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: pxc
      cluster: no-proxysql
      component: no-proxysql-pxc
