apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: hostpath
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  pxc:
    size: 3
    image: percona/percona-xtradb-cluster-operator:1.0.0-pxc
    volumeSpec:
      hostPath:
        path: /tmp/data-dir
        type: Directory
  proxysql:
    enabled: false
  pmm:
    enabled: false
