apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: scheduled-backup
spec:
  secretsName: my-cluster-secrets
  sslSecretName: some-name-ssl
  sslInternalSecretName: some-name-ssl-internal
  pxc:
    size: 3
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-pxc
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  proxysql:
    enabled: true
    size: 1
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-proxysql
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 2Gi
  pmm:
    enabled: false
  backup:
    image: registry.connect.redhat.com/percona/percona-xtradb-cluster-operator-containers:1.0.0-backup
