apiVersion: "pxc.percona.com/v1alpha1"
kind: "PerconaXtraDBCluster"
metadata:
  name: "cluster1"
spec:
  secretsName: my-cluster-secrets
  pxc:
    size: 3
    image: perconalab/pxc-openshift:latest 
    resources:
      requests:
        memory: 1G
        cpu: 700m
      # limits:
      #   memory: 1G
      #   cpu: "1"
    volumeSpec:
      # storageClass: standard
      accessModes: [ "ReadWriteOnce" ]
      size: 6Gi
  proxysql:
    enabled: true
    size: 1
    image: perconalab/proxysql-openshift:latest
    resources:
      requests:
        memory: 1G
        cpu: 700m
      # limits:
      #   memory: 1G
      #   cpu: 700m
    volumeSpec:
      # storageClass: standard
      accessModes: [ "ReadWriteOnce" ]
      size: 2Gi
  pmm:
    enabled: true
    service: monitoring-service
    image: perconalab/pmm-client:latest
    serverUser: pmm