apiVersion: v1
kind: Secret
metadata:
  name: keyring-secret-vault
type: Opaque
stringData:
  keyring_vault_n1.conf: |-
    token = token
    vault_url = http://1.1.1.1:8200
    secret_mount_point = secret
